<?php
require_once __DIR__.'/layout/head.phtml';
?>

<?php
require_once __DIR__.'/layout/header.phtml';
?>

    <style>
		html, body {
		  height: 100%;
		}
		
		body {
		  display: flex;
		  align-items: center;
		  padding-top: 40px;
		  padding-bottom: 40px;
		  background-color: #f5f5f5;
		}
		
		.form-signin {
		  width: 100%;
		  max-width: 330px;
		  padding: 15px;
		  margin: auto;
		}
		.form-signin .checkbox {
		  font-weight: 400;
		}
		.form-signin .form-control {
		  position: relative;
		  box-sizing: border-box;
		  height: auto;
		  padding: 10px;
		  font-size: 16px;
		}
		.form-signin .form-control:focus {
		  z-index: 2;
		}
		.form-signin input[type="email"] {
		  margin-bottom: -1px;
		  border-bottom-right-radius: 0;
		  border-bottom-left-radius: 0;
		}
		.form-signin input[type="password"] {
		  margin-bottom: 10px;
		  border-top-left-radius: 0;
		  border-top-right-radius: 0;
		}
    </style>
    
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

<form class="form-signin text-center">
	<i class="fas fa-database display-4 mb-3"></i>
	
	<div class="input-group mb-3">
	  <div class="input-group-prepend">
	    <label class="input-group-text" for="db_type">Type</label>
	  </div>
	  <select class="custom-select" id="db_type" name="db_type" autofocus required>
	    <option value="">Choose ...</option>
	    <option value="mysql">MySQL / MariaDB</option>
	    <option value="pgsql">PostGre SQL</option>
	  </select>
	</div>
	
	<div class="input-group">
	  <input type="text" class="form-control" id="host" name="host" placeholder="host">
	  <div class="input-group-append">
		  <input type="text" class="" id="port" name="port" placeholder="port" size="5">
	  </div>
	</div>
	<input type="text" id="login" name="login" class="form-control" placeholder="login" required>
	<input type="password" id="password" name="password" class="form-control" placeholder="password" required>

	<button class="btn btn-lg btn-primary btn-block" type="submit">Go</button>
</form>

<?php
require_once __DIR__.'/layout/footer.phtml';
?>

<?php
require_once __DIR__.'/layout/foot.phtml';
?>
