<?php
require_once __DIR__.'/layout/head.phtml';
?>

<?php
require_once __DIR__.'/layout/header.phtml';
?>

<form class="form-signin text-center" action="" method="post">
	<i class="fas fa-database display-4 mb-3"></i>
	
	<div class="input-group mb-3">
	  <div class="input-group-prepend">
	    <label class="input-group-text" for="db_type">Type</label>
	  </div>
	  <select class="custom-select" id="db_type" name="db_type" autofocus required>
	    <option value="">Choose ...</option>
	    <option value="mysql">MySQL / MariaDB</option>
	    <option value="pgsql">PostGre SQL</option>
	  </select>
	</div>
	
	<div class="input-group">
	  <input type="text" class="form-control" id="host" name="host" placeholder="host">
	  <div class="input-group-append">
		  <input type="text" class="" id="port" name="port" placeholder="port" size="5">
	  </div>
	</div>
	<input type="text" id="login" name="login" class="form-control" placeholder="login" required>
	<input type="password" id="password" name="password" class="form-control" placeholder="password" required>

	<button class="btn btn-lg btn-primary btn-block" type="submit">Go</button>
</form>

<?php
require_once __DIR__.'/layout/footer.phtml';
?>

<?php
require_once __DIR__.'/layout/foot.phtml';
?>
